// <auto-generated />
namespace African_Beauty_Trading.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class jeqkbuuqb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jeqkbuuqb));
        
        string IMigrationMetadata.Id
        {
            get { return "202510270033105_jeqkbuuqb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
