// <auto-generated />
namespace African_Beauty_Trading.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class zyhjhh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(zyhjhh));
        
        string IMigrationMetadata.Id
        {
            get { return "202509171959160_zyhjhh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
